version: '2.1'
services:
    db:
        build: ./database
        environment:
            MYSQL_ROOT_PASSWORD: 1234  
            MYSQL_DATABASE: twitterDB  
            MYSQL_USER: api_user  
            MYSQL_PASSWORD: 1234
            
        healthcheck:
            test: "exit 0"
    
    api:
        build: ./api
        depends_on:
            db:
                condition: service_healthy
        entrypoint:
            - /usr/local/bin/docker-entrypoint.sh
        ports:
            - "3000:3000"